name: documents

services:
  documents:
    image: documents
    platform: linux/arm64
    container_name: documents

    security_opt:
      - seccomp:unconfined

    networks:
      - internal

    ports:
      - "8080:8080"

    volumes:
      - ./config.yaml:/app/config.yaml
      - ./prompts.yaml:/app/prompts.yaml

networks:
  internal:
    external: true


