server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  datasource:
    url: jdbc:postgresql://home:5432/private
    username: alex
    password: Manager1
    hikari:
      minimum-idle: 1
      maximum-pool-size: 3

app:
  ai-services: ${AI_SERVICES_URL:http://home:9000}
  ai-timeout-seconds: ${AI_TIMEOUT_SECONDS:30}
  tesseract:
    language: dan
  chunker:
    max-tokens: 4096
    overlap-size: 64
  vector-search:
    boundary:
      - 0.1
      - 0.6

logging:
  level:
    rag.dochandler: INFO
